export const hospitalsData = [
  {
    _id: "demo-1",
    name: "Dhaka Medical College Hospital",
    address: "Secretariat Road, Dhaka 1000",
    phone: "02-9674460",
    email: "dmch@health.gov.bd",
    emergencyHotline: "999",
    ambulance: "01811-458524",
    website: "http://www.dmch.gov.bd",
    status: "approved",
    isActive: true,
    isDemoData: true,
  },
  {
    _id: "demo-2",
    name: "Bangabandhu Sheikh Mujib Medical University",
    address: "Shahbag, Dhaka 1000",
    phone: "02-9668690",
    email: "info@bsmmu.edu.bd",
    emergencyHotline: "999",
    ambulance: "01711-123456",
    website: "https://www.bsmmu.edu.bd",
    status: "approved",
    isActive: true,
    isDemoData: true,
  },
  {
    _id: "demo-3",
    name: "Sir Salimullah Medical College",
    address: "Mitford, Dhaka 1100",
    phone: "02-7319002",
    email: "ssmc@health.gov.bd",
    emergencyHotline: "999",
    ambulance: "01811-234567",
    website: "http://www.ssmc.edu.bd",
    status: "approved",
    isActive: true,
    isDemoData: true,
  },
  {
    _id: "demo-4",
    name: "Chittagong Medical College Hospital",
    address: "K.B. Fazlul Kader Road, Chittagong",
    phone: "031-620308",
    email: "cmch@health.gov.bd",
    emergencyHotline: "999",
    ambulance: "01811-345678",
    website: "http://www.cmch.gov.bd",
    status: "approved",
    isActive: true,
    isDemoData: true,
  },
  {
    _id: "demo-5",
    name: "Rajshahi Medical College Hospital",
    address: "Laxmipur, Rajshahi 6100",
    phone: "0721-772150",
    email: "rmch@health.gov.bd",
    emergencyHotline: "999",
    ambulance: "01811-456789",
    website: "http://www.rmch.gov.bd",
    status: "approved",
    isActive: true,
    isDemoData: true,
  },
];
