export const organizationsData = {
  national: [
    {
      id: 1,
      name: "Bangladesh Red Crescent Society (BDRCS)",
      description:
        "Operates 10 blood centers nationwide, including in Dhaka, Chattogram, Sylhet, Rajshahi, Dinajpur, Jessore, Natore, Magura, and Gopalganj.",
      contact: "01811 458524 (9:00 AM – 5:00 PM)",
      website: "https://bdrcs.org/donate-blood/",
      category: "National",
      icon: "🏥",
      bloodInventory: {
        "A+": 45,
        "A-": 12,
        "B+": 38,
        "B-": 8,
        "AB+": 15,
        "AB-": 5,
        "O+": 52,
        "O-": 10,
      },
      pricing: {
        bloodPrice: 1500, // BDT per unit
        processingFee: 200,
        screeningFee: 300,
        serviceCharge: 100,
      },
    },
    {
      id: 2,
      name: "SANDHANI",
      description:
        "A pioneer in voluntary blood donation, established in 1978. Operates units in 25 medical and dental colleges across Bangladesh.",
      website: "https://en.wikipedia.org/wiki/Sandhani",
      category: "National",
      icon: "🩸",
      bloodInventory: {
        "A+": 38,
        "A-": 10,
        "B+": 42,
        "B-": 7,
        "AB+": 18,
        "AB-": 4,
        "O+": 48,
        "O-": 8,
      },
      pricing: {
        bloodPrice: 1200,
        processingFee: 150,
        screeningFee: 250,
        serviceCharge: 50,
      },
    },
    {
      id: 3,
      name: "Medicine Club",
      description:
        "Founded in 1981 at Mymensingh Medical College. Active in 21 medical and dental colleges, focusing on blood donation and thalassemia awareness.",
      website: "https://en.wikipedia.org/wiki/Blood_donation_in_Bangladesh",
      category: "National",
      icon: "💉",
      bloodInventory: {
        "A+": 35,
        "A-": 9,
        "B+": 40,
        "B-": 6,
        "AB+": 14,
        "AB-": 3,
        "O+": 45,
        "O-": 7,
      },
      pricing: {
        bloodPrice: 1300,
        processingFee: 180,
        screeningFee: 280,
        serviceCharge: 70,
      },
    },
    {
      id: 4,
      name: "Badhan",
      description:
        "Established in 1997 by students of Dhaka University. Promotes voluntary blood donation among university students.",
      website: "https://www.spaandanb.org/projects/badhan-btc/",
      category: "National",
      icon: "🎓",
      bloodInventory: {
        "A+": 32,
        "A-": 8,
        "B+": 36,
        "B-": 5,
        "AB+": 12,
        "AB-": 3,
        "O+": 42,
        "O-": 6,
      },
      pricing: {
        bloodPrice: 1100,
        processingFee: 150,
        screeningFee: 250,
        serviceCharge: 50,
      },
    },
    {
      id: 5,
      name: "Quantum Foundation",
      description:
        "Operates a nationwide voluntary blood donation program. Maintains a large database of blood donors.",
      website: "https://blood.quantummethod.org.bd/en",
      category: "National",
      icon: "🔬",
      bloodInventory: {
        "A+": 50,
        "A-": 14,
        "B+": 44,
        "B-": 9,
        "AB+": 20,
        "AB-": 6,
        "O+": 55,
        "O-": 11,
      },
      pricing: {
        bloodPrice: 1400,
        processingFee: 200,
        screeningFee: 300,
        serviceCharge: 100,
      },
    },
  ],
  hospital: [
    {
      id: 11,
      name: "Evercare Hospital Dhaka",
      description:
        "Offers 24-hour blood transfusion services through their Transfusion Medicine Department.",
      contact: "01713 041277",
      website:
        "https://www.evercarebd.com/dhaka/specialities/transfusion-medicine/",
      category: "Hospital",
      icon: "🏨",
      bloodInventory: {
        "A+": 28,
        "A-": 7,
        "B+": 32,
        "B-": 5,
        "AB+": 10,
        "AB-": 3,
        "O+": 35,
        "O-": 6,
      },
      pricing: {
        bloodPrice: 2000,
        processingFee: 300,
        screeningFee: 400,
        serviceCharge: 150,
      },
    },
    {
      id: 12,
      name: "Holy Family Red Crescent Medical College Hospital",
      description:
        "Provides blood donation and transfusion services. Located at 1 Eskaton Garden Road, Dhaka.",
      website: "https://bdrcs.org/blood-program/",
      category: "Hospital",
      icon: "⛪",
      bloodInventory: {
        "A+": 25,
        "A-": 6,
        "B+": 28,
        "B-": 4,
        "AB+": 9,
        "AB-": 2,
        "O+": 32,
        "O-": 5,
      },
      pricing: {
        bloodPrice: 1600,
        processingFee: 220,
        screeningFee: 320,
        serviceCharge: 80,
      },
    },
    {
      id: 13,
      name: "Lab One Blood Bank",
      description:
        "A modern blood bank encouraging voluntary donations and maintaining a donor registry.",
      website: "https://www.labone.org.bd/lab-one-blood-bank/",
      category: "Hospital",
      icon: "🔬",
      bloodInventory: {
        "A+": 30,
        "A-": 8,
        "B+": 34,
        "B-": 6,
        "AB+": 12,
        "AB-": 4,
        "O+": 38,
        "O-": 7,
      },
      pricing: {
        bloodPrice: 1800,
        processingFee: 250,
        screeningFee: 350,
        serviceCharge: 120,
      },
    },
  ],
  digital: [
    {
      id: 15,
      name: "Smart Blood Donor Management System (SBDMS)",
      description:
        "Streamlines blood donations, vital for thalassemia patients.",
      website: "https://sbdms.hupbd.org/",
      category: "Digital",
      icon: "💻",
      bloodInventory: {
        "A+": 22,
        "A-": 5,
        "B+": 26,
        "B-": 4,
        "AB+": 8,
        "AB-": 2,
        "O+": 28,
        "O-": 5,
      },
      pricing: {
        bloodPrice: 1350,
        processingFee: 180,
        screeningFee: 280,
        serviceCharge: 90,
      },
    },
    {
      id: 16,
      name: "Blood Donors Club, Bangladesh",
      description: "A community of voluntary blood donors.",
      website: "https://en.wikipedia.org/wiki/Blood_donation_in_Bangladesh",
      category: "Digital",
      icon: "👥",
      bloodInventory: {
        "A+": 20,
        "A-": 4,
        "B+": 24,
        "B-": 3,
        "AB+": 7,
        "AB-": 2,
        "O+": 26,
        "O-": 4,
      },
      pricing: {
        bloodPrice: 1250,
        processingFee: 160,
        screeningFee: 260,
        serviceCharge: 60,
      },
    },
  ],
};
