export const hospitals = [
  {
    id: 1,
    name: "Evercare Hospital Dhaka",
    emergencyHotline: "10678",
    ambulance: "+880 1714-090000",
    address: "Plot 81, Block-E, Bashundhara R/A, Dhaka 1229",
    website: "https://www.evercarebd.com",
  },
  {
    id: 2,
    name: "United Hospital Limited",
    emergencyContact: "01914-001234 / 01914-001232",
    address: "Plot 15, Road 71, Gulshan, Dhaka 1212",
    website: "https://uhlbd.com",
  },
  {
    id: 3,
    name: "Square Hospital",
    emergencyHotline: "10616",
    landline: "+88 02 8144400",
    mobile: "+88 01713-377775",
    address:
      "18/F, Bir Uttam Qazi Nuruzzaman Sarak, West Panthapath, Dhaka 1205",
    website: "https://www.squarehospital.com",
  },
  {
    id: 4,
    name: "Bangladesh Specialized Hospital",
    emergencyContact: "01313-777771",
    address: "21 Shyamoli, Mirpur Road, Dhaka 1207",
    website: "https://bdspecializedhospital.com",
  },
  {
    id: 5,
    name: "Dhaka Medical College Hospital (DMCH)",
    address: "Secretariat Road, Dhaka 1000",
    website: "http://www.dmc.gov.bd",
  },
  {
    id: 6,
    name: "Bangabandhu Sheikh Mujib Medical University (BSMMU)",
    address: "Shahbagh, Dhaka 1000",
    website: "https://www.bsmmu.edu.bd",
  },
  {
    id: 7,
    name: "Labaid Specialized Hospital",
    address: "26 Green Road, Dhaka 1205",
    website: "https://www.labaidgroup.com",
  },
  {
    id: 8,
    name: "BIRDEM General Hospital",
    emergencyContact: "02-41060479-80 (Ext: 2302, 2301)",
    address: "122 Kazi Nazrul Islam Avenue, Shahbagh, Dhaka 1000",
    website: "https://birdembd.org",
  },
  {
    id: 9,
    name: "BRB Hospital Limited",
    contact: "09610-010647",
    address: "77/A, East Rajabazar, Panthapath, Dhaka 1215",
    website: "https://www.brbhospital.com",
  },
  {
    id: 10,
    name: "Anwar Khan Modern Medical College Hospital",
    contact: "02-58616074",
    address: "House 17, Road 8, Dhanmondi, Dhaka 1205",
    website: "https://akmmch.com",
  },
  {
    id: 11,
    name: "Central Hospital Limited",
    contact: "02-41060806",
    address: "House 2, Road 5, Green Road, Dhaka 1205",
    website: "https://centralhospitalltdbd.com",
  },
  {
    id: 12,
    name: "Dhaka Community Hospital Trust",
    contact: "+8801711-194576 / +8801749-765651",
    address: "190/1 Boro Moghbazar Wireless Gate, Dhaka 1217",
    website: "https://dchtrust.org",
  },
  {
    id: 13,
    name: "Dhaka Central International Medical College & Hospital",
    hotline: "10651",
    address: "2/1 Ring Road, Shyamoli, Dhaka 1207",
    website: "https://dcimch.com",
  },
  {
    id: 14,
    name: "Ship International Hospital",
    hotline: "10654",
    emergencyContact: "+8801958-509222",
    address: "House 4, Road 1, Sector 10, Uttara, Dhaka",
    website: "https://shiphospitalbd.com",
  },
  {
    id: 15,
    name: "National Institute of Cancer Research & Hospital (NICRH)",
    address: "Mohakhali, TB Gate Road, Dhaka",
    website: "https://nicrh.gov.bd",
  },
  {
    id: 16,
    name: "National Institute of Burn and Plastic Surgery",
    address: "63 AHM Kamruzzaman Sharani, Chankharpul, Dhaka",
  },
  {
    id: 17,
    name: "Holy Family Red Crescent Medical College Hospital",
    address: "1 Eskaton Garden Road, Ramna, Dhaka 1000",
    website: "https://www.hfrcmc.edu.bd",
  },
  {
    id: 18,
    name: "Enam Medical College & Hospital",
    address: "9/3 Parboti Nagar, Thana Road, Savar, Dhaka",
    website: "https://emcbd.info",
  },
  {
    id: 19,
    name: "Ad-Din Hospital",
    contact: "02-9353391-3",
    address: "Moghbazar, Dhaka",
  },
  {
    id: 20,
    name: "Shaheed Suhrawardy Medical College & Hospital",
    contact: "02-9122560-78",
    address: "Sher-e-Bangla Nagar, College Gate, Dhaka",
  },
];
