export const hospitals = [
  {
    id: 1,
    name: "Evercare Hospital Dhaka",
    emergencyHotline: "10678",
    ambulance: "+880 1714-090000",
    address: "Plot 81, Block-E, Bashundhara R/A, Dhaka 1229",
    website: "https://www.evercarebd.com",
    bloodInventory: {
      "A+": 28,
      "A-": 7,
      "B+": 32,
      "B-": 5,
      "AB+": 10,
      "AB-": 3,
      "O+": 35,
      "O-": 6,
    },
    pricing: {
      bloodPrice: 2200,
      processingFee: 350,
      screeningFee: 450,
      serviceCharge: 200,
      additionalFees: {
        crossMatching: 500,
        storagePerDay: 100,
      },
    },
  },
  {
    id: 2,
    name: "United Hospital Limited",
    emergencyContact: "01914-001234 / 01914-001232",
    address: "Plot 15, Road 71, Gulshan, Dhaka 1212",
    website: "https://uhlbd.com",
    bloodInventory: {
      "A+": 30,
      "A-": 8,
      "B+": 34,
      "B-": 6,
      "AB+": 12,
      "AB-": 4,
      "O+": 38,
      "O-": 7,
    },
    pricing: {
      bloodPrice: 2100,
      processingFee: 320,
      screeningFee: 420,
      serviceCharge: 180,
      additionalFees: {
        crossMatching: 480,
        storagePerDay: 90,
      },
    },
  },
  {
    id: 3,
    name: "Square Hospital",
    emergencyHotline: "10616",
    landline: "+88 02 8144400",
    mobile: "+88 01713-377775",
    address:
      "18/F, Bir Uttam Qazi Nuruzzaman Sarak, West Panthapath, Dhaka 1205",
    website: "https://www.squarehospital.com",
    bloodInventory: {
      "A+": 35,
      "A-": 9,
      "B+": 38,
      "B-": 7,
      "AB+": 14,
      "AB-": 5,
      "O+": 42,
      "O-": 8,
    },
    pricing: {
      bloodPrice: 2000,
      processingFee: 300,
      screeningFee: 400,
      serviceCharge: 150,
      additionalFees: {
        crossMatching: 450,
        storagePerDay: 80,
      },
    },
  },
  {
    id: 4,
    name: "Bangladesh Specialized Hospital",
    emergencyContact: "01313-777771",
    address: "21 Shyamoli, Mirpur Road, Dhaka 1207",
    website: "https://bdspecializedhospital.com",
    bloodInventory: {
      "A+": 25,
      "A-": 6,
      "B+": 28,
      "B-": 5,
      "AB+": 10,
      "AB-": 3,
      "O+": 32,
      "O-": 6,
    },
    pricing: {
      bloodPrice: 1800,
      processingFee: 280,
      screeningFee: 380,
      serviceCharge: 130,
      additionalFees: {
        crossMatching: 420,
        storagePerDay: 70,
      },
    },
  },
  {
    id: 5,
    name: "Dhaka Medical College Hospital (DMCH)",
    address: "Secretariat Road, Dhaka 1000",
    website: "http://www.dmc.gov.bd",
    bloodInventory: {
      "A+": 40,
      "A-": 10,
      "B+": 45,
      "B-": 8,
      "AB+": 16,
      "AB-": 5,
      "O+": 50,
      "O-": 9,
    },
    pricing: {
      bloodPrice: 1200,
      processingFee: 150,
      screeningFee: 250,
      serviceCharge: 50,
      additionalFees: {
        crossMatching: 300,
        storagePerDay: 40,
      },
    },
  },
  {
    id: 6,
    name: "Bangabandhu Sheikh Mujib Medical University (BSMMU)",
    address: "Shahbagh, Dhaka 1000",
    website: "https://www.bsmmu.edu.bd",
    bloodInventory: {
      "A+": 38,
      "A-": 9,
      "B+": 42,
      "B-": 7,
      "AB+": 15,
      "AB-": 4,
      "O+": 48,
      "O-": 8,
    },
    pricing: {
      bloodPrice: 1300,
      processingFee: 180,
      screeningFee: 280,
      serviceCharge: 70,
      additionalFees: {
        crossMatching: 350,
        storagePerDay: 50,
      },
    },
  },
  {
    id: 7,
    name: "Labaid Specialized Hospital",
    address: "26 Green Road, Dhaka 1205",
    website: "https://www.labaidgroup.com",
    bloodInventory: {
      "A+": 32,
      "A-": 8,
      "B+": 35,
      "B-": 6,
      "AB+": 12,
      "AB-": 4,
      "O+": 40,
      "O-": 7,
    },
    pricing: {
      bloodPrice: 1900,
      processingFee: 290,
      screeningFee: 390,
      serviceCharge: 140,
      additionalFees: {
        crossMatching: 440,
        storagePerDay: 75,
      },
    },
  },
  {
    id: 8,
    name: "BIRDEM General Hospital",
    emergencyContact: "02-41060479-80 (Ext: 2302, 2301)",
    address: "122 Kazi Nazrul Islam Avenue, Shahbagh, Dhaka 1000",
    website: "https://birdembd.org",
    bloodInventory: {
      "A+": 30,
      "A-": 7,
      "B+": 33,
      "B-": 6,
      "AB+": 11,
      "AB-": 3,
      "O+": 37,
      "O-": 6,
    },
    pricing: {
      bloodPrice: 1600,
      processingFee: 240,
      screeningFee: 340,
      serviceCharge: 100,
      additionalFees: {
        crossMatching: 380,
        storagePerDay: 60,
      },
    },
  },
  {
    id: 9,
    name: "BRB Hospital Limited",
    contact: "09610-010647",
    address: "77/A, East Rajabazar, Panthapath, Dhaka 1215",
    website: "https://www.brbhospital.com",
    bloodInventory: {
      "A+": 28,
      "A-": 6,
      "B+": 30,
      "B-": 5,
      "AB+": 10,
      "AB-": 3,
      "O+": 34,
      "O-": 6,
    },
    pricing: {
      bloodPrice: 1700,
      processingFee: 260,
      screeningFee: 360,
      serviceCharge: 110,
      additionalFees: {
        crossMatching: 400,
        storagePerDay: 65,
      },
    },
  },
  {
    id: 10,
    name: "Anwar Khan Modern Medical College Hospital",
    contact: "02-58616074",
    address: "House 17, Road 8, Dhanmondi, Dhaka 1205",
    website: "https://akmmch.com",
    bloodInventory: {
      "A+": 26,
      "A-": 6,
      "B+": 29,
      "B-": 5,
      "AB+": 9,
      "AB-": 2,
      "O+": 32,
      "O-": 5,
    },
    pricing: {
      bloodPrice: 1650,
      processingFee: 250,
      screeningFee: 350,
      serviceCharge: 105,
      additionalFees: {
        crossMatching: 390,
        storagePerDay: 62,
      },
    },
  },
  {
    id: 11,
    name: "Central Hospital Limited",
    contact: "02-41060806",
    address: "House 2, Road 5, Green Road, Dhaka 1205",
    website: "https://centralhospitalltdbd.com",
    bloodInventory: {
      "A+": 24,
      "A-": 5,
      "B+": 27,
      "B-": 4,
      "AB+": 8,
      "AB-": 2,
      "O+": 30,
      "O-": 5,
    },
    pricing: {
      bloodPrice: 1750,
      processingFee: 270,
      screeningFee: 370,
      serviceCharge: 120,
      additionalFees: {
        crossMatching: 410,
        storagePerDay: 68,
      },
    },
  },
  {
    id: 12,
    name: "Dhaka Community Hospital Trust",
    contact: "+8801711-194576 / +8801749-765651",
    address: "190/1 Boro Moghbazar Wireless Gate, Dhaka 1217",
    website: "https://dchtrust.org",
    bloodInventory: {
      "A+": 22,
      "A-": 5,
      "B+": 25,
      "B-": 4,
      "AB+": 7,
      "AB-": 2,
      "O+": 28,
      "O-": 4,
    },
    pricing: {
      bloodPrice: 1550,
      processingFee: 230,
      screeningFee: 330,
      serviceCharge: 95,
      additionalFees: {
        crossMatching: 370,
        storagePerDay: 58,
      },
    },
  },
  {
    id: 13,
    name: "Dhaka Central International Medical College & Hospital",
    hotline: "10651",
    address: "2/1 Ring Road, Shyamoli, Dhaka 1207",
    website: "https://dcimch.com",
    bloodInventory: {
      "A+": 20,
      "A-": 4,
      "B+": 23,
      "B-": 3,
      "AB+": 6,
      "AB-": 2,
      "O+": 26,
      "O-": 4,
    },
    pricing: {
      bloodPrice: 1600,
      processingFee: 240,
      screeningFee: 340,
      serviceCharge: 100,
      additionalFees: {
        crossMatching: 380,
        storagePerDay: 60,
      },
    },
  },
  {
    id: 14,
    name: "Ship International Hospital",
    hotline: "10654",
    emergencyContact: "+8801958-509222",
    address: "House 4, Road 1, Sector 10, Uttara, Dhaka",
    website: "https://shiphospitalbd.com",
    bloodInventory: {
      "A+": 27,
      "A-": 6,
      "B+": 30,
      "B-": 5,
      "AB+": 9,
      "AB-": 3,
      "O+": 33,
      "O-": 6,
    },
    pricing: {
      bloodPrice: 1850,
      processingFee: 285,
      screeningFee: 385,
      serviceCharge: 135,
      additionalFees: {
        crossMatching: 430,
        storagePerDay: 72,
      },
    },
  },
  {
    id: 15,
    name: "National Institute of Cancer Research & Hospital (NICRH)",
    address: "Mohakhali, TB Gate Road, Dhaka",
    website: "https://nicrh.gov.bd",
    bloodInventory: {
      "A+": 35,
      "A-": 8,
      "B+": 38,
      "B-": 7,
      "AB+": 13,
      "AB-": 4,
      "O+": 42,
      "O-": 7,
    },
    pricing: {
      bloodPrice: 1400,
      processingFee: 200,
      screeningFee: 300,
      serviceCharge: 80,
      additionalFees: {
        crossMatching: 360,
        storagePerDay: 55,
      },
    },
  },
  {
    id: 16,
    name: "National Institute of Burn and Plastic Surgery",
    address: "63 AHM Kamruzzaman Sharani, Chankharpul, Dhaka",
    bloodInventory: {
      "A+": 18,
      "A-": 4,
      "B+": 21,
      "B-": 3,
      "AB+": 6,
      "AB-": 2,
      "O+": 24,
      "O-": 4,
    },
    pricing: {
      bloodPrice: 1350,
      processingFee: 190,
      screeningFee: 290,
      serviceCharge: 75,
      additionalFees: {
        crossMatching: 340,
        storagePerDay: 52,
      },
    },
  },
  {
    id: 17,
    name: "Holy Family Red Crescent Medical College Hospital",
    address: "1 Eskaton Garden Road, Ramna, Dhaka 1000",
    website: "https://www.hfrcmc.edu.bd",
    bloodInventory: {
      "A+": 32,
      "A-": 7,
      "B+": 35,
      "B-": 6,
      "AB+": 12,
      "AB-": 4,
      "O+": 40,
      "O-": 7,
    },
    pricing: {
      bloodPrice: 1500,
      processingFee: 220,
      screeningFee: 320,
      serviceCharge: 85,
      additionalFees: {
        crossMatching: 365,
        storagePerDay: 56,
      },
    },
  },
  {
    id: 18,
    name: "Enam Medical College & Hospital",
    address: "9/3 Parboti Nagar, Thana Road, Savar, Dhaka",
    website: "https://emcbd.info",
    bloodInventory: {
      "A+": 25,
      "A-": 6,
      "B+": 28,
      "B-": 5,
      "AB+": 9,
      "AB-": 3,
      "O+": 32,
      "O-": 6,
    },
    pricing: {
      bloodPrice: 1450,
      processingFee: 210,
      screeningFee: 310,
      serviceCharge: 82,
      additionalFees: {
        crossMatching: 355,
        storagePerDay: 54,
      },
    },
  },
  {
    id: 19,
    name: "Ad-Din Hospital",
    contact: "02-9353391-3",
    address: "Moghbazar, Dhaka",
    bloodInventory: {
      "A+": 23,
      "A-": 5,
      "B+": 26,
      "B-": 4,
      "AB+": 8,
      "AB-": 2,
      "O+": 29,
      "O-": 5,
    },
    pricing: {
      bloodPrice: 1550,
      processingFee: 230,
      screeningFee: 330,
      serviceCharge: 95,
      additionalFees: {
        crossMatching: 370,
        storagePerDay: 58,
      },
    },
  },
  {
    id: 20,
    name: "Shaheed Suhrawardy Medical College & Hospital",
    contact: "02-9122560-78",
    address: "Sher-e-Bangla Nagar, College Gate, Dhaka",
    bloodInventory: {
      "A+": 36,
      "A-": 9,
      "B+": 40,
      "B-": 7,
      "AB+": 14,
      "AB-": 5,
      "O+": 44,
      "O-": 8,
    },
    pricing: {
      bloodPrice: 1250,
      processingFee: 170,
      screeningFee: 270,
      serviceCharge: 65,
      additionalFees: {
        crossMatching: 330,
        storagePerDay: 48,
      },
    },
  },
];
